# Generated by Django 4.1.6 on 2023-04-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Equipo',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Seleccion',
            new_name='seleccion',
        ),
    ]
